spring:
  data:
    mongodb:
      uri: mongodb://172.31.5.254:27017,172.31.25.162:27017/wb24?replicaset=rs-wb
      database: wb24
      username: wb24-admin
      password: wb24-admin
      authentication-database: wb24
